# Generated by Django 5.0.6 on 2024-06-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityclasses',
            name='duration',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
